---
- name: Background twitter tools
  hosts: "{{ host_machine_dns }}" 
  remote_user: "{{ user_name }}"
  become: yes

  vars_files:
  - ../config/group_vars/all

  vars:
    app_base_path: "{{ background_tool_base_path }}"
    user_name: "{{ app_admin }}"
    run_path: "{{background_tool_docker_path}}"

  tasks:
    - name: Starting TweetsFetcher background tool
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        build: yes
        restarted: true
      
    - name: Starting DM bucket monitor tool
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        files: docker-compose-dmbucket_monitor.yml
        build: yes
        restarted: true

    - name: Starting DM Check tools
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        files: docker-compose-dmcheck_batch1.yml
        build: yes
        restarted: true

    - name: Starting Follower check monitor tool
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        files: docker-compose-followerbucket_monitor.yml
        build: yes
        restarted: true

    - name: Starting Follower Check tools
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        files: docker-compose-followercheck_batch1.yml
        build: yes
        restarted: true

    - name: Starting Following check monitor tool
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        files: docker-compose-followingbucket_monitor.yml
        build: yes
        restarted: true

    - name: Starting Following Check tools
      docker_compose:
        project_src: "{{ run_path }}"
        project_name: "{{ deployment_name }}"
        files: docker-compose-followingcheck_batch1.yml
        build: yes
        restarted: true