---
- name: Neo4J Database
  hosts: "{{ host_machine_dns }}" 
  remote_user: "{{ user_name }}"
  become: yes

  vars_files:
  - ../config/group_vars/all

  vars:
    app_base_path: "{{ neo4j_code_base_path }}"
    user_name: "{{ neo4j_admin }}"

  tasks:
    - name: Starting neo4j database
      shell: 
        cmd: sudo bash run_neo4j.bash -p {{ deployment_name }} up -d >>ansible_out.txt
        chdir: "{{ app_base_path }}"
    - debug:
        var: output
