---
- name: Neo4J Database
  hosts: sarvat.com 
  remote_user: neo4jadmin
  become: yes
  tasks:
    - name: Starting neo4j database
      shell: 
        cmd: sudo bash run_neo4j.bash up -d >>ansible_out.txt
        chdir: /home/neo4jadmin/predeploy/neo4j-docker/
    - debug:
        var: output